name = input('Hey! What is your name? ')
print('Nice to meet you '+ name + '!')
age = input ('How old are you? ')
print( 'woah, ' + age + 'years old?! I was born yesterday.')
feeling = input('How are you doing today?')
print('that is great to hear' + feeling.lower () + 'That is wonderful to hear!')